### ISSUE TITLE
gui-console shows error

### ISSUE THREAD

**Issue by jvonau** [XSCE/xsce#295]
attached screenshot
![gui-error](https://cloud.githubusercontent.com/assets/5579710/7262148/f6de3e90-e83c-11e4-9d86-a130a7a5c76d.png)

**Comment by tim-moody** [comment]
Just guessing I would say that xsce.ini contains text that doesn't parse as json. I tried enclosing especially the descriptions in quotes.Sent from my BlackBerry® PlayBook™www.blackberry.comFrom: "Jerry Vonau" <notifications@github.com>To: "XSCE/xsce" <xsce@noreply.github.com>Sent: 21 April, 2015 4:42 PMSubject: [xsce] gui-console shows error (#295)attached screenshot

**Comment by georgejhunt** [comment]
Bingo,

I saw that one of my edits put {#   something #} rather than {{ something
}} in the INI file. I'll find and fix.

**Comment by tim-moody** [comment]
the generic err handler should report the command it is executing, but because everything is a callback it's not trivial.Sent from my BlackBerry® PlayBook™www.blackberry.comFrom: "georgejhunt" <notifications@github.com>To: "XSCE/xsce" <xsce@noreply.github.com>CC: "Tim Moody" <tim@timmoody.com>Sent: 21 April, 2015 5:24 PMSubject: Re: [xsce] gui-console shows error (#295)Bingo,

I saw that one of my edits put {#   something #} rather than {{ something
}} in the INI file. I'll find and fix.

**Comment by georgejhunt** [comment]
It is indeed confusing. I have an ini file from a previous run which looks
like

[idmgr]
name = idmgr
description = Idmgr is an automatic identity manager for XO clients which
enables automatic backup
enabled = {# xo_services_enabled #}

But the playbook is no different than all the others, and no typo is
apparent. xo_services_enabled is defined in var/default_vars.yml -- so it's
not that the variable was not set.

Maybe it is because it is the last line of the file without a crlf.

But then on the current run (I had already started another new run on
hash:ce09bf, on x86_64, i3NUC) and I don't get the same (but I was running
runansible, rather than just ./install-console"

Do you see Jerry, any other problems with your ini file?

**Comment by jvonau** [comment]
I don't see any apparent issues with the ini file, contents of xsce.ini
after booting livecd:

[location]
xsce_base = /opt/schoolserver
xsce_dir = /opt/schoolserver/xsce

[version]
xsce_branch = install
xsce_commit = ce097bfe5eb94cdfdbfdc02cc8ca482884733b67
xsce_uuid = d81a4aa3-a02e-4e34-a340-fabee23d795d
install_date = 2015-04-21T06:42:34Z
install_xo = none

[runtime]
runtime_branch = install
runtime_commit = ce097bfe5eb94cdfdbfdc02cc8ca482884733b67
runtime_date = 2015-04-21T21:11:50Z
runtime_php = /usr/lib64/php
runtime_preload = True

[network]
wan_enabled = True
detected_gateway = p2p1
user_gateway = auto
computed_gateway = p2p1
lan_enabled = True
num_lan_interfaces = 1
discovered_wireless_iface = wlp0s6u2
xsce_wireless_lan_iface = wlp0s6u2
detected_lan = none
user_lan = auto
computed_lan = br0
xsce_network_mode = Gateway

[kiwix]
name = kiwix-serve
description = "kiwix-serve is a web server for zim files"
kiwix_url = /kiwix
kiwix_path = /opt/schoolserver/kiwix
kiwix_port = 3000
xsce_zim_path = /library/zims
kiwix_library_xml = /library/zims/library.xml
kiwix_content_path = /library/zims/content
enabled = False

[squid]
name = squid
description = Squid caches web pages the first time they are accessed, and
pulls them from the cache thereafter
enabled = True

[dansguardian]
name = dansguardian
description = Dansguardian searches web content for sexual references and
denies access when found
enabled = True

[wondershaper]
name = wondershaper
description = Wondershaper is a command line tool to set maximum transfer
rates for network adapters
enabled = False

I don't believe the error is related to the ini file at all, I can suppress
the the noted error by deleting the json files in /etc/xsce, but that
breaks stuff on the utilities tab. Guess its looking to load the json file
and can't proceed past that point to load the other modules.

**Comment by tim-moody** [comment]
as I said, it was a guess.  try get storage info on util and see if that gives the same error.  run cmdsrv from cmdline and see if it throwing an error.  what is the os, what devs?Sent from my BlackBerry® PlayBook™www.blackberry.comFrom: "Jerry Vonau" <notifications@github.com>To: "XSCE/xsce" <xsce@noreply.github.com>CC: "Tim Moody" <tim@timmoody.com>Sent: 21 April, 2015 11:22 PMSubject: Re: [xsce] gui-console shows error (#295)I don't see any apparent issues with the ini file, contents of xsce.ini
after booting livecd:

[location]
xsce_base = /opt/schoolserver
xsce_dir = /opt/schoolserver/xsce

[version]
xsce_branch = install
xsce_commit = ce097bfe5eb94cdfdbfdc02cc8ca482884733b67
xsce_uuid = d81a4aa3-a02e-4e34-a340-fabee23d795d
install_date = 2015-04-21T06:42:34Z
install_xo = none

[runtime]
runtime_branch = install
runtime_commit = ce097bfe5eb94cdfdbfdc02cc8ca482884733b67
runtime_date = 2015-04-21T21:11:50Z
runtime_php = /usr/lib64/php
runtime_preload = True

[network]
wan_enabled = True
detected_gateway = p2p1
user_gateway = auto
computed_gateway = p2p1
lan_enabled = True
num_lan_interfaces = 1
discovered_wireless_iface = wlp0s6u2
xsce_wireless_lan_iface = wlp0s6u2
detected_lan = none
user_lan = auto
computed_lan = br0
xsce_network_mode = Gateway

[kiwix]
name = kiwix-serve
description = "kiwix-serve is a web server for zim files"
kiwix_url = /kiwix
kiwix_path = /opt/schoolserver/kiwix
kiwix_port = 3000
xsce_zim_path = /library/zims
kiwix_library_xml = /library/zims/library.xml
kiwix_content_path = /library/zims/content
enabled = False

[squid]
name = squid
description = Squid caches web pages the first time they are accessed, and
pulls them from the cache thereafter
enabled = True

[dansguardian]
name = dansguardian
description = Dansguardian searches web content for sexual references and
denies access when found
enabled = True

[wondershaper]
name = wondershaper
description = Wondershaper is a command line tool to set maximum transfer
rates for network adapters
enabled = False

I don't believe the error is related to the ini file at all, I can suppress
the the noted error by deleting the json files in /etc/xsce, but that
breaks stuff on the utilities tab. Guess its looking to load the json file
and can't proceed past that point to load the other modules.

**Comment by tim-moody** [comment]
what is in /etc/xsce/kiwix catalog, is there a symlink from html/common/assets?try refresh kiwix catalog or libr on inst contentSent from my BlackBerry® PlayBook™www.blackberry.comFrom: "Jerry Vonau" <notifications@github.com>To: "XSCE/xsce" <xsce@noreply.github.com>CC: "Tim Moody" <tim@timmoody.com>Sent: 21 April, 2015 11:22 PMSubject: Re: [xsce] gui-console shows error (#295)I don't see any apparent issues with the ini file, contents of xsce.ini
after booting livecd:

[location]
xsce_base = /opt/schoolserver
xsce_dir = /opt/schoolserver/xsce

[version]
xsce_branch = install
xsce_commit = ce097bfe5eb94cdfdbfdc02cc8ca482884733b67
xsce_uuid = d81a4aa3-a02e-4e34-a340-fabee23d795d
install_date = 2015-04-21T06:42:34Z
install_xo = none

[runtime]
runtime_branch = install
runtime_commit = ce097bfe5eb94cdfdbfdc02cc8ca482884733b67
runtime_date = 2015-04-21T21:11:50Z
runtime_php = /usr/lib64/php
runtime_preload = True

[network]
wan_enabled = True
detected_gateway = p2p1
user_gateway = auto
computed_gateway = p2p1
lan_enabled = True
num_lan_interfaces = 1
discovered_wireless_iface = wlp0s6u2
xsce_wireless_lan_iface = wlp0s6u2
detected_lan = none
user_lan = auto
computed_lan = br0
xsce_network_mode = Gateway

[kiwix]
name = kiwix-serve
description = "kiwix-serve is a web server for zim files"
kiwix_url = /kiwix
kiwix_path = /opt/schoolserver/kiwix
kiwix_port = 3000
xsce_zim_path = /library/zims
kiwix_library_xml = /library/zims/library.xml
kiwix_content_path = /library/zims/content
enabled = False

[squid]
name = squid
description = Squid caches web pages the first time they are accessed, and
pulls them from the cache thereafter
enabled = True

[dansguardian]
name = dansguardian
description = Dansguardian searches web content for sexual references and
denies access when found
enabled = True

[wondershaper]
name = wondershaper
description = Wondershaper is a command line tool to set maximum transfer
rates for network adapters
enabled = False

I don't believe the error is related to the ini file at all, I can suppress
the the noted error by deleting the json files in /etc/xsce, but that
breaks stuff on the utilities tab. Guess its looking to load the json file
and can't proceed past that point to load the other modules.

**Comment by jvonau** [comment]
Think I figured it out, when this error occurs there is a cd/dvd present in
/dev/sr0 resulting in *get_stor_devs.sh* receiving a warning about a
read-only device from parted. I'll see if excluding sr0 from the grep
results in no warning.

**Comment by jvonau** [comment]
Nope, removing the cdrom/dvd from the machine results in "display system
storage" working correctly but the noted error persists. Going to validate
all the json files with an online tool and see if anything comes of that.

**Comment by jvonau** [comment]
using http://codebeautify.org/jsonvalidate reports invalid data for:
https://raw.githubusercontent.com/jvonau/xsce/master/roles/2-common/files/html/assets/lang_codes.json

**Comment by jvonau** [comment]
https://www.jsoneditoronline.org/?url=https://raw.githubusercontent.com/jvonau/xsce/master/roles/2-common/files/html/assets/lang_codes.json
show the same error and when I open lang_codes.json in nano I get warning
about being in mac format.

**Comment by tim-moody** [comment]
something's funny, because that file hasn't changed for awhile, but got moved.  not sure I tested on f18.  the python parser is not as bothered  by the unicode chars as some of the online parsers.in chrome take f12 and go to console.  type langCodes to see if it is empty.Sent from my BlackBerry® PlayBook™www.blackberry.comFrom: "Jerry Vonau" <notifications@github.com>To: "XSCE/xsce" <xsce@noreply.github.com>CC: "Tim Moody" <tim@timmoody.com>Sent: 22 April, 2015 10:06 AMSubject: Re: [xsce] gui-console shows error (#295)using http://codebeautify.org/jsonvalidate reports invalid data for:
https://raw.githubusercontent.com/jvonau/xsce/master/roles/2-common/files/html/assets/lang_codes.json

**Comment by tim-moody** [comment]
can you do a diff on the file that was in master a week or even a month ago, before the move.Sent from my BlackBerry® PlayBook™www.blackberry.comFrom: "Jerry Vonau" <notifications@github.com>To: "XSCE/xsce" <xsce@noreply.github.com>CC: "Tim Moody" <tim@timmoody.com>Sent: 22 April, 2015 10:19 AMSubject: Re: [xsce] gui-console shows error (#295)https://www.jsoneditoronline.org/?url=https://raw.githubusercontent.com/jvonau/xsce/master/roles/2-common/files/html/assets/lang_codes.json
show the same error and when I open lang_codes.json in nano I get warning
about being in mac format.

**Comment by jvonau** [comment]
It looks like zim_lang.json was replaced with lang_codes.json in the last
week. I've just rewrote the file with a non mac editor and the json passes
the online tests in PR #298

**Comment by tim-moody** [comment]
What happens when you go to install content install zims, do all the languages show up and have their unicode names?  Still a mystery as I don't use a Mac and didn't change the file recently.  Also, I think zim_langs is quite an old name. Sent from my BlackBerry® PlayBook™www.blackberry.comFrom: "Jerry Vonau" <notifications@github.com>To: "XSCE/xsce" <xsce@noreply.github.com>CC: "Tim Moody" <tim@timmoody.com>Sent: 22 April, 2015 10:47 AMSubject: Re: [xsce] gui-console shows error (#295)It looks like zim_lang.json was replaced with lang_codes.json in the last
week. I've just rewrote the file with a non mac editor and the json passes
the online tests in PR #298

**Comment by jvonau** [comment]
On Wed, Apr 22, 2015 at 9:55 AM, Tim Moody <notifications@github.com> wrote:

> What happens when you go to install content install zims, do all the
> languages show up and have their unicode names?


When I press the "Select Language" button a list is not presented.


> Still a mystery as I don't use a Mac and didn't change the file recently.


Tracked the change down to commit e7fab876304bd87e54a74642def8498af8330b54
where zim_lang.json was replaced with lang_codes.json. Maybe it was
downloaded and used unchanged?


> Also, I think zim_langs is quite an old name.


changed April 15~ish just before it was moved to 2-common.

**Comment by jvonau** [comment]
current master
https://raw.githubusercontent.com/XSCE/xsce/master/roles/2-common/files/html/assets/lang_codes.json

old zim_lang.json :
https://github.com/XSCE/xsce/blob/04a383a0e159017bac8bb9397b719eba1b2a3ccc/roles/xsce-admin/files/cmdsrv/zim_json/zim_langs.json

**Comment by tim-moody** [comment]
The two files should be the same, just renamed and moved. I produced it from a lot of merging of files.Before  I left I tested on a f20 vm and did not see this problem.  Do you see it on that issue?Sent from my BlackBerry® PlayBook™www.blackberry.comFrom: "Jerry Vonau" <notifications@github.com>To: "XSCE/xsce" <xsce@noreply.github.com>CC: "Tim Moody" <tim@timmoody.com>Sent: 22 April, 2015 12:51 PMSubject: Re: [xsce] gui-console shows error (#295)current master
https://raw.githubusercontent.com/XSCE/xsce/master/roles/2-common/files/html/assets/lang_codes.json

old zim_lang.json :
https://github.com/XSCE/xsce/blob/04a383a0e159017bac8bb9397b719eba1b2a3ccc/roles/xsce-admin/files/cmdsrv/zim_json/zim_langs.json

**Comment by jvonau** [comment]
Three things were issues in this one:
1. The mac encoding issue, the two files mentioned have different contents
and the revised one in the PR fixes the error.
2. download2 ran the whole playbook, confusing cmd_srv as the library.xml
file was created but blank, moving the download to main.yml will fix that.
3. I mistakenly changed the section label from kiwix-serve for the xsce.ini
while there was installation issues while using kiwix-serve_enabled, that
got changed to kiwix_serve_enabled fixing that issue.

All in PR #298, I'll push it and retest.

**Comment by tim-moody** [comment]
sounds to me like item 1 is irrelevant and the real problem was not having a valid library.xml in item 2.  please confirm that your new lang_codes gets a full list of languages and they have native names displayed.
what matters is whether python can parse the file, not some arbitrary online service.  Also, be aware that nano doesn't handle unicode as I remember.
as far as item 3 is concerned, what is the name of the kiwix server, is it not kiwix-serve, hence the original name of the flag.

Date: Wed, 22 Apr 2015 11:55:26 -0700

**Comment by tim-moody** [comment]
btw, I just logged into timxsce on the vpn, which represents my last commit.  The console does not show the error you reported.

From: tim@timmoody.com
To: reply@reply.github.com
Subject: RE: [xsce] gui-console shows error (#295)
Date: Wed, 22 Apr 2015 19:11:04 +0000




sounds to me like item 1 is irrelevant and the real problem was not having a valid library.xml in item 2.  please confirm that your new lang_codes gets a full list of languages and they have native names displayed.
what matters is whether python can parse the file, not some arbitrary online service.  Also, be aware that nano doesn't handle unicode as I remember.
as far as item 3 is concerned, what is the name of the kiwix server, is it not kiwix-serve, hence the original name of the flag.

Date: Wed, 22 Apr 2015 11:55:26 -0700

**Comment by jvonau** [comment]
leaving PR #298 open for when it maybe deemed needed, pushed the other non json changes in #299

**Comment by georgejhunt** [comment]
Just did a clean instal of i686 on 2830NUC, up to console, enabled all the
checkboxes, ran to completion -- on FC21, with most recent master which is
now c279ab6.....

Clean, no errors, alerts,

**Comment by jvonau** [comment]
FWIW, did a F21-net-install, used the standard directions. At the end of install-console the machine rebooted, used firefox(37.0.2) to log into /admin and the error is present. Wondering if this is browser related?

xsce.ini at the end of install-console:
[location]
xsce_base = /opt/schoolserver
xsce_dir = /opt/schoolserver/xsce

[version]
xsce_branch = master
xsce_commit = c279ab697bb8fd2a13fd881506ea4af9d77ae936
xsce_uuid = ff779d07-333b-449c-a492-54f3726af2de
install_date = 2015-04-23T23:00:44Z
install_xo = none

[runtime]
runtime_branch = master
runtime_commit = c279ab697bb8fd2a13fd881506ea4af9d77ae936
runtime_date = 2015-04-23T23:00:44Z
runtime_php = /usr/lib/php
runtime_preload = False

[network]
wan_enabled = True
detected_gateway = enp0s3
user_gateway = auto
computed_gateway = enp0s3
lan_enabled = True
num_lan_interfaces = 1
discovered_wireless_iface = none
xsce_wireless_lan_iface = none
detected_lan = enp0s8
user_lan = auto
computed_lan = enp0s8
xsce_network_mode = Gateway

[squid]
name = squid
description = Squid caches web pages the first time they are accessed, and pulls them from the cache thereafter
enabled = True

[dansguardian]
name = dansguardian
description = Dansguardian searches web content for sexual references and denies access when found
enabled = True

[wondershaper]
name = wondershaper
description = Wondershaper is a command line tool to set maximum transfer rates for network adapters
enabled = False

**Comment by m-anish** [comment]
FWIW, I get the same error. I am on commit 24f6e6bf4d6cf2b5c4062e837ae2b52ee1533930
(Thu Apr 16 11:43:35 2015 -0400 ---- Merge pull request #281 from tim-moody/adm-fix)

Just refreshing the page reproduces the error. 

The machine is a fedora 21-x86_64/Intel NUC

**Comment by jvonau** [comment]
George confirmed issue with firefox. merged #298
