### ISSUE TITLE
Is bangalore.html supposed to be part of upstream master?

### ISSUE THREAD

**Issue by m-anish** [XSCE/xsce#816]
Is `xsce/roles/portal/files/alt-home/bangalore.html` supposed to be part of **upstream** master?

**Comment by tim-moody** [comment]
Yes. My plan has been to throw in everything to serve as samples.

Also many menudefs still need work, especially the ones that are generated from Rachel.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by m-anish** [comment]
sample for what? isn't that what the actual homepage is supposed to be. 

If it is supposed to be a sample, shouldn't it be in some _doc_ folder, or named as index.html.sample?

**Comment by tim-moody** [comment]
this was a late addition and there is a lot to be done.  more than 80% of the files were generated from rachel and some, like kalite and zims, should be removed as we do thing differently than rachel.

still, I'm not clear as to what the issue is.  bangalore.html will only appear if explicitly entered into the browser and no one looks at doc directories.  the default index.html is a kitchen sink.  if the menu you want is similar to one of the samples that sample is probably a good place to start.

**Comment by m-anish** [comment]
The issue is that bangalore.html looks like something that should be found in a downstream implementation of XSCE and not in upstream master -- atleast not without proper documentation. 

I am using 3 different homepages for three different deployments in India, all of which are far better than the old xs-portal homepage. I dont expect to find them in upstream master, unless they become generic pieces which can be customized by deployments, with proper documentation as to how this is to be done. 

Just my two cents.

**Comment by georgejhunt** [comment]
The whole menuing, portal, approach in 6.2 has shifted, and support for content is shifted to https://github.com/tim-moody/iiab-menu
