### ISSUE TITLE
Moodle does not install successfully on raspbian, debian

### ISSUE THREAD

**Issue by georgejhunt** [XSCE/xsce#854]

**Comment by tim-moody** [comment]
on deb 8.6 vm installs, but when enabled

TASK [moodle : Start postgresql-xs] ********************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "Job for postgresql-xs.service failed. See 'systemctl status postgresql-xs.service' and 'journalctl -xn' for details.\n"}

**Comment by tim-moody** [comment]
looks like postgresql already running

**Comment by tim-moody** [comment]
postgresql.service is running so postgresql-xs service can not start

**Comment by tim-moody** [comment]
is there any reason not to use stock postgresql with moodle 3.1+?

**Comment by tim-moody** [comment]
short term fix in PR 863

**Comment by georgejhunt** [comment]
On a clean install, failed again. This time the step which changed ownership to www-data looked like it had executed in the log, but ownership was not changed.  Put a when: True, and reran ./runtages moodle. Then it worked. So it may be an ansible bug.
So I still do not understand the cause of the failure

**Comment by georgejhunt** [comment]
Turned out to be a strange situation where the installer set owner of moodle directory to root, and prevente apache from writing the config file. 

Fixed and tested

**Comment by tim-moody** [comment]
moodle now installs, but schoolserver/moodle give a 500 error

[Mon Jan 30 15:59:18.124233 2017] [:error] [pid 23592] [client 172.18.100.205:5227] PHP Fatal error:  require_once(): Failed opening required 'config.php' (include_path='.:/usr/share/php:/usr/share/pear') in /opt/schoolserver/moodle/index.php on line 30

**Comment by tim-moody** [comment]
on debian on nuc

TASK [moodle : Start postgresql-xs] ********************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to restart service postgresql-xs: Job for postgresql-xs.service failed. See 'systemctl status postgresql-xs.service' and 'journalctl -xn' for details.\n"}
        to retry, use: --limit @/opt/schoolserver/xsce/xsce.retry

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=406  changed=82   unreachable=0    failed=1

root@schoolserver:/opt/schoolserver/xsce# journalctl -xn
-- Logs begin at Mon 2017-01-30 22:44:51 EST, end at Tue 2017-01-31 18:56:45 EST. --
Jan 31 18:56:35 schoolserver.lan systemd[1]: [/etc/systemd/system/calibre-serve.service:10] Unknown lvalue 'TimeoutStartSec' in section 'Install'
Jan 31 18:56:44 schoolserver.lan systemd[1]: Starting PostgreSQL database server...
-- Subject: Unit postgresql-xs.service has begun with start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit postgresql-xs.service has begun starting up.
Jan 31 18:56:44 schoolserver.lan pg_ctl[16386]: LOG:  skipping missing configuration file "/library/pgsql-xs/postgresql.auto.conf"
Jan 31 18:56:44 schoolserver.lan pg_ctl[16386]: LOG:  skipping missing configuration file "/library/pgsql-xs/postgresql.auto.conf"
Jan 31 18:56:44 schoolserver.lan pg_ctl[16386]: FATAL:  could not open file "/library/pgsql-xs/PG_VERSION": Permission denied
Jan 31 18:56:45 schoolserver.lan pg_ctl[16386]: pg_ctl: could not start server
Jan 31 18:56:45 schoolserver.lan pg_ctl[16386]: Examine the log output.
Jan 31 18:56:45 schoolserver.lan systemd[1]: postgresql-xs.service: control process exited, code=exited status=1
Jan 31 18:56:45 schoolserver.lan systemd[1]: Failed to start PostgreSQL database server.
-- Subject: Unit postgresql-xs.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit postgresql-xs.service has failed.
--
-- The result is failed.
Jan 31 18:56:45 schoolserver.lan systemd[1]: Unit postgresql-xs.service entered failed state.
root@schoolserver:/opt/schoolserver/xsce# systemctl status postgresql-xs
● postgresql-xs.service - PostgreSQL database server
   Loaded: loaded (/etc/systemd/system/postgresql-xs.service; static)
   Active: failed (Result: exit-code) since Tue 2017-01-31 18:56:45 EST; 1min 18s ago
  Process: 16386 ExecStart=/usr/lib/postgresql/9.4/bin/pg_ctl start -D ${PGDATA} -s -w -t ${PGSTARTTIMEOUT} (code=exited, status=1/FAILURE)

Jan 31 18:56:44 schoolserver.lan pg_ctl[16386]: LOG:  skipping missing configuration file "/library/pgsql-xs/postgresql.auto.conf"
Jan 31 18:56:44 schoolserver.lan pg_ctl[16386]: LOG:  skipping missing configuration file "/library/pgsql-xs/postgresql.auto.conf"
Jan 31 18:56:44 schoolserver.lan pg_ctl[16386]: FATAL:  could not open file "/library/pgsql-xs/PG_VERSION": Permission denied
Jan 31 18:56:45 schoolserver.lan pg_ctl[16386]: pg_ctl: could not start server
Jan 31 18:56:45 schoolserver.lan pg_ctl[16386]: Examine the log output.
Jan 31 18:56:45 schoolserver.lan systemd[1]: postgresql-xs.service: control process exited, code=exited status=1
Jan 31 18:56:45 schoolserver.lan systemd[1]: Failed to start PostgreSQL database server.
Jan 31 18:56:45 schoolserver.lan systemd[1]: Unit postgresql-xs.service entered failed state.

**Comment by tim-moody** [comment]
The last errors are upgrade problems not likely to be seen by others. If using a library partition previously used on centos, the user names are wrong for apache, postgresql, etc. and they don't get fixed when the directory already exists.
