### ISSUE TITLE
when logged into server can not resolve server name

### ISSUE THREAD

**Issue by tim-moody** [XSCE/xsce#859]
if you ssh into the server and ping server name the name will not resolve

after some time it will resolve

**Comment by holta** [comment]
As mentioned to @georgejhunt in #861 names are not resolvable by the student on the machine itself, perhaps due to Raspbian's /etc/resolv.conf behaving differently than Fedora/CentOS ?  e.g. /etc/resolv.conf on my RPi3's appears as follows:

   ```
# Generated by resolvconf
   nameserver 192.168.0.1
   nameserver 172.18.96.1
```

Background: Jerry Vonau emailed us Jan 14 "No, that is not normal.​ ​I'll go with /etc/resolv.conf does not have nameserver 127.0.0.1 but is pointing upstream to dhcp provided nameservers"

I'm willing to assist in any experimentation necessary to find the cause and later fix this wonky resolv.conf, so that our documentation (most all of which assumes schoolserver.lan works) remains useful to kids & all!

**Comment by georgejhunt** [comment]
I found this debian doc which suggests that an entry needs to be made in /etc/network/interfaces which gives direction to resolvconf daemon
https://wiki.debian.org/NetworkConfiguration#The_resolvconf_program

**Comment by holta** [comment]
@jvonau might know but I don't know how to modify /etc/network/interfaces -- FYI it appears as follows:

```
# interfaces(5) file used by ifup(8) and ifdown(8)

# Please note that this file is written to be used with dhcpcd
# For static IP, consult /etc/dhcpcd.conf and 'man dhcpcd.conf'

# Include files from /etc/network/interfaces.d:
source-directory /etc/network/interfaces.d

auto lo
iface lo inet loopback

iface eth0 inet manual

allow-hotplug wlan0
iface wlan0 inet manual
    wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf

allow-hotplug wlan1
iface wlan1 inet manual
    wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf
```

**Comment by georgejhunt** [comment]
I'm going to need to modify the interfaces template, to get the wired
lancontroller to work.  So I'll try to do this one at the same time.

**Comment by georgejhunt** [comment]
the resolvconf package has a head file which is tacked on to the head of resolv.conf whenever it is rewritten. So we can put our nameserver 127.0.0.1 and seach lan there. And it does not delete the dhcp nameserver, so there is less risk of stalling an install if bind9 is not up yet, or malfunctioning.
