### ISSUE TITLE
box wanted as a school server alias

### ISSUE THREAD

**Issue by georgejhunt** [XSCE/xsce#861]

**Comment by holta** [comment]
Also http://box.lan should work.  The full set of 6 should be:

   {box, box.lan, school, school.lan, schoolserver, schoolserver.lan}

Related: #859 causing most all our training/help documents to become invalid (or need updating) if these 6 names are not resolvable by the operator/student on the machine itself, perhaps due to Raspbian's /etc/resolv.conf behaving differently than Fedora/CentOS ?  e.g. /etc/resolv.conf on my RPi3's appears as follows:

```
   # Generated by resolvconf
   nameserver 192.168.0.1
   nameserver 172.18.96.1
```

**Comment by georgejhunt** [comment]
box added to named local database. Http://box.lan and http://box tested
